version: '3'

services:
  business-central:
    image: quay.io/kiegroup/business-central-workbench-showcase:7.73.0.Final
    ports:
      - "8080:8080"
      - "8001:8001"
  kie-server:
    image: quay.io/kiegroup/kie-server-showcase:7.73.0.Final
    ports:
      - "8180:8080"
      - "8007:8001"
    environment:
      KIE_SERVER_ID: sample-server
      KIE_SERVER_LOCATION: http://192.168.68.114:8180/kie-server/services/rest/server
      KIE_SERVER_CONTROLLER: http://192.168.68.114:8080/business-central/rest/controller
      KIE_MAVEN_REPO: http://192.168.68.114:8080/business-central/maven2
    depends_on:
      - business-central